apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dzaw269v0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dzaw269v0-java-springboot-gitops